"""
Java Backend career roadmap data — levels Intern → Senior.
Mirrors the javabuilder.online structure adapted for Serein's dark theme.
"""

CAREER_LEVELS = [
    {"id": "intern", "emoji": "🌱", "label": "Intern", "sublabel": None},
    {"id": "fresher", "emoji": "🚀", "label": "Fresher", "sublabel": None},
    {"id": "junior", "emoji": "⭐", "label": "Junior", "sublabel": "1-2 years exp"},
    {"id": "middle", "emoji": "🔥", "label": "Middle", "sublabel": "2-4 years exp"},
    {"id": "senior", "emoji": "👑", "label": "Senior", "sublabel": "4+ years exp"},
]

ROADMAP_QUOTE = {
    "vi": "Mỗi dòng code bạn viết hôm nay là nền tảng cho sự nghiệp ngày mai. Hãy kiên trì! 💪",
    "en": "Every line of code you write today is the foundation for tomorrow's career. Stay persistent! 💪",
}

# badge_level: beginner | intermediate | advanced
ROADMAP_TOPICS = {
    "intern": [
        {
            "order": 1,
            "title": "Java Core",
            "subtitle_vi": "Nền tảng lập trình Java",
            "subtitle_en": "Java Programming Foundation",
            "badge_level": "beginner",
            "duration_weeks": 3,
            "subtopics": [
                "Kiểu dữ liệu, biến, toán tử",
                "Câu lệnh điều kiện và vòng lặp",
                "Mảng và String",
                "Hướng đối tượng (OOP) cơ bản",
                "Interface và Abstract class",
                "Exception handling",
                "Collections Framework",
            ],
        },
        {
            "order": 2,
            "title": "SQL & Database",
            "subtitle_vi": "Làm việc với Cơ sở dữ liệu",
            "subtitle_en": "Working with Databases",
            "badge_level": "beginner",
            "duration_weeks": 2,
            "subtopics": [
                "SELECT, INSERT, UPDATE, DELETE",
                "JOIN, GROUP BY, HAVING",
                "Index và tối ưu câu truy vấn",
                "Transactions và ACID",
            ],
        },
        {
            "order": 3,
            "title": "JDBC",
            "subtitle_vi": "Kết nối Java với Database",
            "subtitle_en": "Connecting Java with Database",
            "badge_level": "beginner",
            "duration_weeks": 1,
            "subtopics": [
                "DriverManager và Connection",
                "PreparedStatement vs Statement",
                "ResultSet xử lý kết quả",
            ],
        },
        {
            "order": 4,
            "title": "Basic Hibernate & JPA",
            "subtitle_vi": "Object-Relational Mapping",
            "subtitle_en": "Object-Relational Mapping",
            "badge_level": "beginner",
            "duration_weeks": 2,
            "subtopics": [
                "@Entity, @Table, @Id",
                "EntityManager và persistence context",
                "JPQL cơ bản",
                "Quan hệ @OneToMany, @ManyToOne",
            ],
        },
        {
            "order": 5,
            "title": "Spring Core & DI",
            "subtitle_vi": "Dependency Injection",
            "subtitle_en": "Dependency Injection",
            "badge_level": "beginner",
            "duration_weeks": 1,
            "subtopics": [
                "@Component, @Service, @Repository",
                "@Autowired và constructor injection",
                "ApplicationContext và Bean lifecycle",
                "Spring Configuration (@Bean, @Configuration)",
            ],
        },
        {
            "order": 6,
            "title": "Basic Spring Boot",
            "subtitle_vi": "Xây dựng ứng dụng CRUD",
            "subtitle_en": "Building CRUD Applications",
            "badge_level": "intermediate",
            "duration_weeks": 3,
            "subtopics": [
                "Spring Initializr và project structure",
                "@RestController, @GetMapping, @PostMapping",
                "Request/Response với @RequestBody, @PathVariable",
                "Spring Data JPA Repository",
                "application.properties / application.yml",
            ],
        },
        {
            "order": 7,
            "title": "Validation & Exception Handling",
            "subtitle_vi": "Xử lý lỗi và Validation",
            "subtitle_en": "Error Handling & Validation",
            "badge_level": "beginner",
            "duration_weeks": 1,
            "subtopics": [
                "@Valid, @NotBlank, @Size, @Email",
                "@ControllerAdvice và @ExceptionHandler",
                "ResponseEntity và HTTP status codes",
            ],
        },
        {
            "order": 8,
            "title": "Git & Postman",
            "subtitle_vi": "Công cụ cơ bản",
            "subtitle_en": "Basic Tools",
            "badge_level": "beginner",
            "duration_weeks": 1,
            "subtopics": [
                "Git init, add, commit, push, pull",
                "Branch và merge strategy",
                "Postman: test REST API",
            ],
        },
    ],
    "fresher": [
        {
            "order": 1,
            "title": "Spring Security",
            "subtitle_vi": "Bảo mật ứng dụng",
            "subtitle_en": "Application Security",
            "badge_level": "intermediate",
            "duration_weeks": 2,
            "subtopics": [
                "SecurityFilterChain cấu hình",
                "JWT Authentication flow",
                "BCrypt password hashing",
                "@PreAuthorize và phân quyền",
            ],
        },
        {
            "order": 2,
            "title": "RESTful API Design",
            "subtitle_vi": "Thiết kế API chuẩn REST",
            "subtitle_en": "RESTful API Design",
            "badge_level": "intermediate",
            "duration_weeks": 2,
            "subtopics": [
                "REST principles và HTTP verbs",
                "API versioning (/api/v1/...)",
                "Pagination và filtering",
                "DTO pattern (Request/Response separation)",
                "MapStruct mapper",
            ],
        },
        {
            "order": 3,
            "title": "Advanced Spring Data JPA",
            "subtitle_vi": "JPA nâng cao",
            "subtitle_en": "Advanced JPA",
            "badge_level": "intermediate",
            "duration_weeks": 2,
            "subtopics": [
                "JPA Specifications",
                "Custom @Query với JPQL / native SQL",
                "Lazy vs Eager loading",
                "N+1 problem và giải pháp",
                "Auditing (@CreatedDate, @LastModifiedDate)",
            ],
        },
        {
            "order": 4,
            "title": "Logging & Monitoring",
            "subtitle_vi": "Ghi log và theo dõi",
            "subtitle_en": "Logging & Monitoring",
            "badge_level": "beginner",
            "duration_weeks": 1,
            "subtopics": [
                "Slf4j / Logback configuration",
                "Log levels: DEBUG, INFO, WARN, ERROR",
                "Spring Boot Actuator endpoints",
            ],
        },
        {
            "order": 5,
            "title": "Docker Basics",
            "subtitle_vi": "Container hóa ứng dụng",
            "subtitle_en": "Containerizing Applications",
            "badge_level": "intermediate",
            "duration_weeks": 2,
            "subtopics": [
                "Dockerfile cho Spring Boot app",
                "docker build, run, push",
                "docker-compose cho multi-container",
                "Environment variables trong container",
            ],
        },
        {
            "order": 6,
            "title": "Unit Testing",
            "subtitle_vi": "Kiểm thử đơn vị",
            "subtitle_en": "Unit Testing",
            "badge_level": "intermediate",
            "duration_weeks": 2,
            "subtopics": [
                "JUnit 5 cơ bản",
                "Mockito mock và stub",
                "@SpringBootTest vs @WebMvcTest",
                "Test coverage với Jacoco",
            ],
        },
    ],
    "junior": [
        {
            "order": 1,
            "title": "Spring Cloud Microservices",
            "subtitle_vi": "Kiến trúc phân tán",
            "subtitle_en": "Distributed Architecture",
            "badge_level": "intermediate",
            "duration_weeks": 3,
            "subtopics": [
                "Service discovery với Eureka",
                "API Gateway với Spring Cloud Gateway",
                "Config Server tập trung",
                "Feign Client giao tiếp service-to-service",
            ],
        },
        {
            "order": 2,
            "title": "Message Queue (Kafka / RabbitMQ)",
            "subtitle_vi": "Giao tiếp bất đồng bộ",
            "subtitle_en": "Asynchronous Messaging",
            "badge_level": "intermediate",
            "duration_weeks": 2,
            "subtopics": [
                "Producer / Consumer pattern",
                "Kafka topics và partitions",
                "RabbitMQ exchanges và queues",
                "Dead letter queue handling",
            ],
        },
        {
            "order": 3,
            "title": "Redis Caching",
            "subtitle_vi": "Cache và lưu trữ nhanh",
            "subtitle_en": "Caching & Fast Storage",
            "badge_level": "intermediate",
            "duration_weeks": 2,
            "subtopics": [
                "@Cacheable, @CacheEvict",
                "Redis data structures",
                "Session management với Redis",
                "Cache invalidation strategies",
            ],
        },
        {
            "order": 4,
            "title": "CI/CD Pipeline",
            "subtitle_vi": "Tự động hóa triển khai",
            "subtitle_en": "Deployment Automation",
            "badge_level": "intermediate",
            "duration_weeks": 2,
            "subtopics": [
                "GitHub Actions workflow",
                "Maven build và test automation",
                "Docker image build & push to registry",
                "Deploy lên VPS / cloud",
            ],
        },
        {
            "order": 5,
            "title": "Database Design",
            "subtitle_vi": "Thiết kế cơ sở dữ liệu",
            "subtitle_en": "Database Design",
            "badge_level": "intermediate",
            "duration_weeks": 2,
            "subtopics": [
                "Normalization (1NF → 3NF)",
                "ERD diagram",
                "Database migration với Flyway/Liquibase",
                "Indexing strategies",
            ],
        },
    ],
    "middle": [
        {
            "order": 1,
            "title": "System Design",
            "subtitle_vi": "Thiết kế hệ thống lớn",
            "subtitle_en": "Large-scale System Design",
            "badge_level": "advanced",
            "duration_weeks": 4,
            "subtopics": [
                "CAP theorem",
                "Load balancing strategies",
                "Horizontal vs Vertical scaling",
                "Database sharding và replication",
                "CDN và caching layers",
            ],
        },
        {
            "order": 2,
            "title": "Advanced Security",
            "subtitle_vi": "Bảo mật nâng cao",
            "subtitle_en": "Advanced Security",
            "badge_level": "advanced",
            "duration_weeks": 3,
            "subtopics": [
                "OAuth2 và OpenID Connect",
                "PKCE flow cho SPA",
                "Rate limiting và DDoS protection",
                "OWASP Top 10",
                "Security audit và penetration testing",
            ],
        },
        {
            "order": 3,
            "title": "Performance Optimization",
            "subtitle_vi": "Tối ưu hiệu năng",
            "subtitle_en": "Performance Optimization",
            "badge_level": "advanced",
            "duration_weeks": 3,
            "subtopics": [
                "Profiling với VisualVM / async-profiler",
                "JVM tuning (GC, heap size)",
                "Database query optimization",
                "Connection pooling (HikariCP)",
                "Async processing với CompletableFuture",
            ],
        },
        {
            "order": 4,
            "title": "Resilience Patterns",
            "subtitle_vi": "Khả năng phục hồi hệ thống",
            "subtitle_en": "Resilience Patterns",
            "badge_level": "advanced",
            "duration_weeks": 2,
            "subtopics": [
                "Circuit Breaker (Resilience4j)",
                "Retry và Fallback patterns",
                "Bulkhead pattern",
                "Timeout và backpressure",
            ],
        },
    ],
    "senior": [
        {
            "order": 1,
            "title": "Architecture Patterns",
            "subtitle_vi": "Các mô hình kiến trúc",
            "subtitle_en": "Architecture Patterns",
            "badge_level": "advanced",
            "duration_weeks": 4,
            "subtopics": [
                "Domain-Driven Design (DDD)",
                "Event-Driven Architecture",
                "CQRS & Event Sourcing",
                "Hexagonal (Ports & Adapters) architecture",
                "Saga pattern cho distributed transactions",
            ],
        },
        {
            "order": 2,
            "title": "Kubernetes & Cloud Native",
            "subtitle_vi": "Triển khai cloud native",
            "subtitle_en": "Cloud Native Deployment",
            "badge_level": "advanced",
            "duration_weeks": 4,
            "subtopics": [
                "Kubernetes Pods, Deployments, Services",
                "Helm charts",
                "Horizontal Pod Autoscaler",
                "Service mesh (Istio basics)",
                "Observability: Prometheus + Grafana",
            ],
        },
        {
            "order": 3,
            "title": "Technical Leadership",
            "subtitle_vi": "Kỹ năng dẫn dắt kỹ thuật",
            "subtitle_en": "Technical Leadership",
            "badge_level": "advanced",
            "duration_weeks": 3,
            "subtopics": [
                "Code review best practices",
                "RFC / ADR writing",
                "Mentoring junior developers",
                "Tech debt management",
                "Estimation và planning",
            ],
        },
        {
            "order": 4,
            "title": "Observability & SRE",
            "subtitle_vi": "Giám sát và độ tin cậy",
            "subtitle_en": "Observability & Reliability",
            "badge_level": "advanced",
            "duration_weeks": 3,
            "subtopics": [
                "Distributed tracing (Jaeger / Zipkin)",
                "SLO, SLA, SLI metrics",
                "Incident response runbooks",
                "Chaos engineering",
            ],
        },
    ],
}
