"""Chinese language course content — 3 courses with rich flashcards, quiz questions, and Hanzi."""

CHINESE_SURVIVAL_CARDS = [
    ("你好", "Hello", "nǐ hǎo", "Common greeting"),
    ("谢谢", "Thank you", "xiè xie", "Polite response"),
    ("明天", "Tomorrow", "míng tiān", "Scheduling word"),
    ("再见", "Goodbye", "zài jiàn", "Parting phrase"),
    ("对不起", "Sorry", "duì bu qǐ", "Apology"),
    ("没关系", "It's okay", "méi guān xi", "Response to apology"),
    ("请", "Please", "qǐng", "Polite request"),
    ("是", "Yes / To be", "shì", "Affirmative"),
    ("不是", "No / Not to be", "bú shì", "Negative"),
    ("我", "I / Me", "wǒ", "First person pronoun"),
    ("你", "You", "nǐ", "Second person pronoun"),
    ("他/她", "He / She", "tā", "Third person pronoun"),
    ("这个", "This", "zhè ge", "Demonstrative"),
    ("那个", "That", "nà ge", "Demonstrative"),
    ("多少钱", "How much?", "duō shǎo qián", "Shopping phrase"),
    ("在哪里", "Where?", "zài nǎ lǐ", "Asking location"),
    ("什么", "What?", "shén me", "Question word"),
    ("怎么", "How?", "zěn me", "Question word"),
    ("好的", "Okay / Good", "hǎo de", "Agreement"),
    ("不好意思", "Excuse me", "bù hǎo yì si", "Polite interruption"),
    ("一", "One", "yī", "Number 1"),
    ("二", "Two", "èr", "Number 2"),
    ("三", "Three", "sān", "Number 3"),
    ("四", "Four", "sì", "Number 4"),
    ("五", "Five", "wǔ", "Number 5"),
    ("六", "Six", "liù", "Number 6"),
    ("七", "Seven", "qī", "Number 7"),
    ("八", "Eight", "bā", "Number 8"),
    ("九", "Nine", "jiǔ", "Number 9"),
    ("十", "Ten", "shí", "Number 10"),
    ("今天", "Today", "jīn tiān", "Time word"),
    ("昨天", "Yesterday", "zuó tiān", "Time word"),
    ("现在", "Now", "xiàn zài", "Time word"),
    ("吃", "To eat", "chī", "Common verb"),
    ("喝", "To drink", "hē", "Common verb"),
    ("去", "To go", "qù", "Common verb"),
    ("来", "To come", "lái", "Common verb"),
    ("看", "To look / watch", "kàn", "Common verb"),
    ("说", "To speak", "shuō", "Common verb"),
    ("听", "To listen", "tīng", "Common verb"),
]

CHINESE_SURVIVAL_HANZI = ["你", "好", "学", "习", "中", "文", "大", "小", "人", "天", "日", "月"]

CHINESE_SURVIVAL_QUIZ = [
    {"q": "\"你好\" có nghĩa là gì?", "type": "multiple_choice", "options": ["Goodbye", "Hello", "Thank you", "Sorry"], "answer": "Hello", "explain": "你好 (nǐ hǎo) là lời chào phổ biến nhất trong tiếng Trung."},
    {"q": "Phiên âm pinyin của 谢谢 là gì?", "type": "multiple_choice", "options": ["xié xie", "xiè xie", "shè she", "xiě xiě"], "answer": "xiè xie", "explain": "谢谢 phát âm là xiè xie, thanh 4 + thanh nhẹ."},
    {"q": "Từ nào nghĩa là 'Tomorrow'?", "type": "multiple_choice", "options": ["昨天", "今天", "明天", "现在"], "answer": "明天", "explain": "明天 (míng tiān) = ngày mai. 昨天 = hôm qua, 今天 = hôm nay."},
    {"q": "Điền vào chỗ trống: 你___吗？(How are you?)", "type": "fill_blank", "options": [], "answer": "好", "explain": "你好吗？(nǐ hǎo ma?) = Bạn khỏe không?"},
    {"q": "数字 \"七\" bằng bao nhiêu?", "type": "multiple_choice", "options": ["5", "6", "7", "8"], "answer": "7", "explain": "七 (qī) = 7."},
    {"q": "\"对不起\" dùng trong tình huống nào?", "type": "multiple_choice", "options": ["Chào hỏi", "Xin lỗi", "Cảm ơn", "Tạm biệt"], "answer": "Xin lỗi", "explain": "对不起 (duì bu qǐ) là cách xin lỗi phổ biến."},
    {"q": "Điền pinyin đúng cho 再见: ___", "type": "fill_blank", "options": [], "answer": "zài jiàn", "explain": "再见 = zài jiàn, nghĩa là tạm biệt."},
    {"q": "\"多少钱\" hỏi về điều gì?", "type": "multiple_choice", "options": ["Thời gian", "Địa điểm", "Giá tiền", "Tên"], "answer": "Giá tiền", "explain": "多少钱 (duō shǎo qián) = bao nhiêu tiền?"},
]

CHINESE_HSK1_CARDS = [
    ("爸爸", "Father / Dad", "bà ba", "Family member"),
    ("妈妈", "Mother / Mom", "mā ma", "Family member"),
    ("儿子", "Son", "ér zi", "Family member"),
    ("女儿", "Daughter", "nǚ ér", "Family member"),
    ("朋友", "Friend", "péng yǒu", "Social relationship"),
    ("老师", "Teacher", "lǎo shī", "Occupation"),
    ("学生", "Student", "xué shēng", "Occupation"),
    ("医生", "Doctor", "yī shēng", "Occupation"),
    ("工作", "To work / Job", "gōng zuò", "Daily activity"),
    ("学校", "School", "xué xiào", "Place"),
    ("医院", "Hospital", "yī yuàn", "Place"),
    ("商店", "Shop / Store", "shāng diàn", "Place"),
    ("饭店", "Restaurant", "fàn diàn", "Place"),
    ("中国", "China", "zhōng guó", "Country"),
    ("北京", "Beijing", "běi jīng", "City"),
    ("水", "Water", "shuǐ", "Noun"),
    ("茶", "Tea", "chá", "Noun"),
    ("米饭", "Rice", "mǐ fàn", "Food"),
    ("菜", "Vegetable / Dish", "cài", "Food"),
    ("苹果", "Apple", "píng guǒ", "Food"),
    ("杯子", "Cup", "bēi zi", "Object"),
    ("书", "Book", "shū", "Object"),
    ("电脑", "Computer", "diàn nǎo", "Object"),
    ("电话", "Telephone", "diàn huà", "Object"),
    ("钱", "Money", "qián", "Noun"),
    ("读", "To read", "dú", "Verb"),
    ("写", "To write", "xiě", "Verb"),
    ("买", "To buy", "mǎi", "Verb"),
    ("卖", "To sell", "mài", "Verb — note tone difference with 买"),
    ("住", "To live / reside", "zhù", "Verb"),
    ("想", "To want / think", "xiǎng", "Verb"),
    ("喜欢", "To like", "xǐ huān", "Verb"),
    ("会", "Can / able to", "huì", "Modal verb"),
    ("能", "Can / physically able", "néng", "Modal verb"),
    ("大", "Big", "dà", "Adjective"),
    ("小", "Small", "xiǎo", "Adjective"),
    ("多", "Many / Much", "duō", "Adjective"),
    ("少", "Few / Little", "shǎo", "Adjective"),
    ("热", "Hot", "rè", "Adjective"),
    ("冷", "Cold", "lěng", "Adjective"),
    ("高兴", "Happy", "gāo xìng", "Adjective"),
    ("漂亮", "Beautiful", "piào liang", "Adjective"),
    ("年", "Year", "nián", "Time word"),
    ("月", "Month", "yuè", "Time word"),
    ("日", "Day / Sun", "rì", "Time word"),
    ("星期", "Week", "xīng qī", "Time word"),
    ("上午", "Morning (AM)", "shàng wǔ", "Time word"),
    ("下午", "Afternoon (PM)", "xià wǔ", "Time word"),
    ("岁", "Age (years old)", "suì", "Measure word for age"),
    ("块", "Yuan / piece", "kuài", "Measure word for money"),
]

CHINESE_HSK1_QUIZ = [
    {"q": "\"学生\" có nghĩa là gì?", "type": "multiple_choice", "options": ["Teacher", "Student", "Doctor", "Friend"], "answer": "Student", "explain": "学生 (xué shēng) = học sinh / sinh viên."},
    {"q": "Pinyin của 医院 là gì?", "type": "multiple_choice", "options": ["yī yuán", "yī yuàn", "yì yuàn", "yí yuàn"], "answer": "yī yuàn", "explain": "医院 = yī yuàn = bệnh viện."},
    {"q": "Điền vào: 我___喝茶。(I like to drink tea)", "type": "fill_blank", "options": [], "answer": "喜欢", "explain": "我喜欢喝茶 = Tôi thích uống trà."},
    {"q": "Từ nào nghĩa là 'to buy'?", "type": "multiple_choice", "options": ["卖 mài", "买 mǎi", "卖 mǎi", "买 mài"], "answer": "买 mǎi", "explain": "买 (mǎi, thanh 3) = mua. 卖 (mài, thanh 4) = bán."},
    {"q": "\"高兴\" biểu đạt cảm xúc gì?", "type": "multiple_choice", "options": ["Buồn", "Tức giận", "Vui vẻ", "Sợ hãi"], "answer": "Vui vẻ", "explain": "高兴 (gāo xìng) = vui vẻ, phấn khởi."},
    {"q": "Từ nào chỉ 'nước'?", "type": "multiple_choice", "options": ["茶", "水", "酒", "米饭"], "answer": "水", "explain": "水 (shuǐ) = nước."},
    {"q": "Điền pinyin: 电脑 = ___", "type": "fill_blank", "options": [], "answer": "diàn nǎo", "explain": "电脑 (diàn nǎo) = máy tính."},
    {"q": "\"冷\" và \"热\" là cặp từ gì?", "type": "multiple_choice", "options": ["Lớn - Nhỏ", "Nóng - Lạnh", "Nhiều - Ít", "Cao - Thấp"], "answer": "Nóng - Lạnh", "explain": "热 (rè) = nóng, 冷 (lěng) = lạnh."},
]

CHINESE_CONVERSATION_CARDS = [
    ("请问，洗手间在哪里？", "Excuse me, where is the restroom?", "qǐng wèn, xǐ shǒu jiān zài nǎ lǐ?", "Asking for directions"),
    ("我要一杯咖啡", "I want a cup of coffee", "wǒ yào yī bēi kā fēi", "Ordering at café"),
    ("这个多少钱？", "How much is this?", "zhè ge duō shǎo qián?", "Shopping"),
    ("太贵了，便宜一点", "Too expensive, cheaper please", "tài guì le, pián yí yī diǎn", "Bargaining"),
    ("我不懂", "I don't understand", "wǒ bù dǒng", "Clarification"),
    ("请再说一遍", "Please say it again", "qǐng zài shuō yī biàn", "Clarification"),
    ("我是越南人", "I am Vietnamese", "wǒ shì yuè nán rén", "Self-introduction"),
    ("我在学中文", "I am studying Chinese", "wǒ zài xué zhōng wén", "Self-introduction"),
    ("你叫什么名字？", "What is your name?", "nǐ jiào shén me míng zì?", "Meeting someone"),
    ("认识你很高兴", "Nice to meet you", "rèn shí nǐ hěn gāo xìng", "Meeting someone"),
    ("你会说英语吗？", "Can you speak English?", "nǐ huì shuō yīng yǔ ma?", "Communication"),
    ("我要去机场", "I want to go to the airport", "wǒ yào qù jī chǎng", "Transportation"),
    ("请帮我叫出租车", "Please help me call a taxi", "qǐng bāng wǒ jiào chū zū chē", "Transportation"),
    ("菜单在哪里？", "Where is the menu?", "cài dān zài nǎ lǐ?", "Restaurant"),
    ("买单", "Check please / Bill", "mǎi dān", "Restaurant"),
    ("我吃素", "I am vegetarian", "wǒ chī sù", "Dietary preference"),
    ("不辣的", "Not spicy", "bú là de", "Food preference"),
    ("能不能帮我拍照？", "Can you help me take a photo?", "néng bù néng bāng wǒ pāi zhào?", "Tourism"),
    ("这里可以刷卡吗？", "Can I pay by card here?", "zhè lǐ kě yǐ shuā kǎ ma?", "Payment"),
    ("WiFi密码是什么？", "What is the WiFi password?", "WiFi mì mǎ shì shén me?", "At hotel/café"),
]

CHINESE_CONVERSATION_QUIZ = [
    {"q": "Khi muốn hỏi giá tiền, bạn nói gì?", "type": "multiple_choice", "options": ["这个多少钱？", "这个在哪里？", "这个是什么？", "这个好不好？"], "answer": "这个多少钱？", "explain": "多少钱 = bao nhiêu tiền."},
    {"q": "Điền vào: 请___一遍 (Please say it again)", "type": "fill_blank", "options": [], "answer": "再说", "explain": "请再说一遍 = Xin hãy nói lại một lần nữa."},
    {"q": "\"买单\" dùng khi nào?", "type": "multiple_choice", "options": ["Gọi món", "Thanh toán", "Đặt bàn", "Chào hỏi"], "answer": "Thanh toán", "explain": "买单 (mǎi dān) = xin tính tiền / thanh toán."},
    {"q": "Cách tự giới thiệu quốc tịch Việt Nam?", "type": "multiple_choice", "options": ["我是中国人", "我是越南人", "我是日本人", "我是韩国人"], "answer": "我是越南人", "explain": "我是越南人 (wǒ shì yuè nán rén) = Tôi là người Việt Nam."},
    {"q": "Điền: 你___什么名字？(What is your name?)", "type": "fill_blank", "options": [], "answer": "叫", "explain": "你叫什么名字？= Bạn tên là gì?"},
]
