"""English language course content — 3 courses with rich flashcards and quiz questions."""

ENGLISH_COMMUNICATION_CARDS = [
    ("I would like to follow up on...", "Use to continue a previous discussion", None, "I would like to follow up on our meeting."),
    ("Could you clarify...", "Ask for more detail politely", None, "Could you clarify the deadline?"),
    ("In summary", "Signals a concise recap", None, "In summary, we need three changes."),
    ("As per our discussion", "Reference a prior conversation", None, "As per our discussion, I've updated the report."),
    ("Please find attached", "Standard email attachment phrase", None, "Please find attached the Q3 report."),
    ("I appreciate your prompt response", "Thank someone for a quick reply", None, "I appreciate your prompt response on this matter."),
    ("Looking forward to hearing from you", "Polite closing in emails", None, "Looking forward to hearing from you soon."),
    ("Would you mind if I...", "Polite way to ask permission", None, "Would you mind if I rescheduled the meeting?"),
    ("I'm afraid that...", "Softening bad news", None, "I'm afraid that we'll need to postpone."),
    ("With regard to...", "Referring to a specific topic", None, "With regard to the new policy, here are my thoughts."),
    ("To be honest...", "Expressing a frank opinion", None, "To be honest, I think we need a different approach."),
    ("That being said...", "Introducing a contrasting point", None, "The results are good. That being said, we can improve."),
    ("Let me get back to you on that", "Promise to follow up", None, "Good question. Let me get back to you on that."),
    ("Could you elaborate on...", "Ask for more explanation", None, "Could you elaborate on the timeline?"),
    ("I'm reaching out to...", "State purpose of email", None, "I'm reaching out to discuss the project scope."),
    ("As a matter of fact...", "Emphasizing a point", None, "As a matter of fact, sales increased by 20%."),
    ("From my perspective...", "Sharing your viewpoint", None, "From my perspective, this is the best option."),
    ("I'd like to bring to your attention...", "Highlighting something important", None, "I'd like to bring to your attention a small issue."),
    ("Moving forward...", "Talking about future actions", None, "Moving forward, we'll use the new system."),
    ("For your reference", "Providing supplementary info", None, "For your reference, here's the link to the docs."),
    ("I couldn't agree more", "Strong agreement", None, "I couldn't agree more with your analysis."),
    ("That's a valid point", "Acknowledging someone's argument", None, "That's a valid point. Let me reconsider."),
    ("Let's circle back to...", "Returning to a previous topic", None, "Let's circle back to the budget discussion."),
    ("I was wondering if...", "Polite indirect question", None, "I was wondering if you could help me with this."),
    ("Just to confirm...", "Double-checking information", None, "Just to confirm, the deadline is Friday?"),
    ("It goes without saying that...", "Something obvious but worth noting", None, "It goes without saying that quality is our priority."),
    ("I'll keep you posted", "Promise to update later", None, "I'll keep you posted on any changes."),
    ("As soon as possible (ASAP)", "Urgency indicator", None, "Please submit the report ASAP."),
    ("FYI (For Your Information)", "Informal heads-up", None, "FYI, the meeting room changed to B201."),
    ("At your earliest convenience", "Polite urgency", None, "Please review the document at your earliest convenience."),
]

ENGLISH_COMMUNICATION_QUIZ = [
    {"q": "Which phrase is best for starting a follow-up email?", "type": "multiple_choice", "options": ["Hey what's up", "I would like to follow up on...", "Remember me?", "Just checking"], "answer": "I would like to follow up on...", "explain": "Professional and clear — ideal for business emails."},
    {"q": "Fill in: 'Please find ___ the quarterly report.'", "type": "fill_blank", "options": [], "answer": "attached", "explain": "'Please find attached' is the standard email phrase for file attachments."},
    {"q": "Which is the most polite way to disagree?", "type": "multiple_choice", "options": ["You're wrong.", "I see your point, but...", "No way.", "That's stupid."], "answer": "I see your point, but...", "explain": "Acknowledging the other person's view before disagreeing is professional."},
    {"q": "Fill in: 'I'm ___ out to discuss the new project.'", "type": "fill_blank", "options": [], "answer": "reaching", "explain": "'I'm reaching out to...' is a common way to state the purpose of an email."},
    {"q": "'Let me get back to you on that' means:", "type": "multiple_choice", "options": ["I refuse", "I'll respond later", "I don't care", "I agree"], "answer": "I'll respond later", "explain": "This phrase politely indicates you need time to find the answer."},
    {"q": "Which closing is appropriate for a formal email?", "type": "multiple_choice", "options": ["See ya!", "Cheers mate", "Looking forward to hearing from you", "Later!"], "answer": "Looking forward to hearing from you", "explain": "Professional and courteous email closing."},
    {"q": "Fill in: 'Moving ___, we'll implement the new strategy.'", "type": "fill_blank", "options": [], "answer": "forward", "explain": "'Moving forward' = from now on / going ahead."},
    {"q": "'At your earliest convenience' expresses:", "type": "multiple_choice", "options": ["No rush at all", "Extreme anger", "Polite urgency", "Indifference"], "answer": "Polite urgency", "explain": "It's a softer way of saying 'please do this soon'."},
]

ENGLISH_TOEIC_CARDS = [
    ("deadline", "The latest time by which something must be completed", None, "The deadline for the report is next Friday."),
    ("agenda", "A list of items to be discussed at a meeting", None, "Let's review the agenda before the meeting starts."),
    ("negotiate", "To discuss something to reach an agreement", None, "We need to negotiate the contract terms."),
    ("invoice", "A bill for goods or services provided", None, "Please send the invoice to the accounting department."),
    ("revenue", "Income generated from business operations", None, "The company's revenue increased by 15% this quarter."),
    ("budget", "A financial plan for a defined period", None, "We need to stay within the marketing budget."),
    ("implement", "To put a plan or system into effect", None, "We will implement the new policy next month."),
    ("collaborate", "To work jointly with others", None, "Our teams will collaborate on this project."),
    ("efficient", "Achieving maximum productivity with minimum waste", None, "The new system is much more efficient."),
    ("comply", "To act in accordance with rules or requests", None, "All employees must comply with safety regulations."),
    ("initiative", "A new plan or process to achieve something", None, "The green initiative reduced energy costs by 30%."),
    ("quarterly", "Occurring every three months", None, "The quarterly report is due next week."),
    ("prospective", "Expected or likely to happen", None, "We have a meeting with prospective clients."),
    ("allocate", "To distribute resources for a purpose", None, "We need to allocate more budget to R&D."),
    ("postpone", "To delay to a later time", None, "The conference has been postponed until March."),
    ("mandatory", "Required by law or rule; compulsory", None, "Attendance at the safety training is mandatory."),
    ("surplus", "An amount of something left over", None, "The company reported a budget surplus this year."),
    ("deficit", "A shortfall or gap, especially financial", None, "The trade deficit widened in Q2."),
    ("stakeholder", "A person with an interest in a project", None, "We need to consult all stakeholders before deciding."),
    ("benchmark", "A standard for measuring or comparing", None, "This score serves as a benchmark for future tests."),
    ("feasible", "Possible and practical to do", None, "The proposal seems feasible within our budget."),
    ("proficiency", "A high degree of skill or expertise", None, "Language proficiency is required for this position."),
    ("compensation", "Payment or benefits for work done", None, "The compensation package includes health insurance."),
    ("prerequisite", "Something required before something else", None, "A bachelor's degree is a prerequisite for this role."),
    ("fluctuate", "To rise and fall irregularly", None, "Oil prices tend to fluctuate throughout the year."),
    ("merger", "A combination of two companies into one", None, "The merger was approved by both boards."),
    ("warranty", "A guarantee of product quality", None, "The laptop comes with a two-year warranty."),
    ("inventory", "A complete list of items; stock of goods", None, "We need to update the inventory before the audit."),
    ("tentative", "Not certain or fixed; provisional", None, "We have a tentative schedule for the launch."),
    ("reimburse", "To repay money spent by someone else", None, "The company will reimburse your travel expenses."),
]

ENGLISH_TOEIC_QUIZ = [
    {"q": "What does 'deadline' mean?", "type": "multiple_choice", "options": ["A type of meeting", "The last date to complete something", "A financial report", "A work schedule"], "answer": "The last date to complete something", "explain": "Deadline = thời hạn cuối cùng phải hoàn thành."},
    {"q": "Fill in: 'Please send the ___ to the accounting department.'", "type": "fill_blank", "options": [], "answer": "invoice", "explain": "Invoice = hóa đơn thanh toán."},
    {"q": "'Revenue' is best defined as:", "type": "multiple_choice", "options": ["Expenses", "Debt", "Income from business", "Tax payment"], "answer": "Income from business", "explain": "Revenue = doanh thu."},
    {"q": "Fill in: 'All employees must ___ with safety regulations.'", "type": "fill_blank", "options": [], "answer": "comply", "explain": "Comply with = tuân thủ."},
    {"q": "Which word means 'to delay to a later time'?", "type": "multiple_choice", "options": ["Allocate", "Postpone", "Implement", "Negotiate"], "answer": "Postpone", "explain": "Postpone = hoãn lại."},
    {"q": "'Mandatory' means:", "type": "multiple_choice", "options": ["Optional", "Required", "Recommended", "Suggested"], "answer": "Required", "explain": "Mandatory = bắt buộc."},
    {"q": "Fill in: 'The company will ___ your travel expenses.'", "type": "fill_blank", "options": [], "answer": "reimburse", "explain": "Reimburse = hoàn trả chi phí."},
    {"q": "'Tentative' most closely means:", "type": "multiple_choice", "options": ["Final", "Certain", "Provisional", "Permanent"], "answer": "Provisional", "explain": "Tentative = tạm thời, chưa chắc chắn."},
]

ENGLISH_GRAMMAR_CARDS = [
    ("Present Simple", "Used for habits, facts, and routines", None, "She works at a hospital. / Water boils at 100°C."),
    ("Present Continuous", "Action happening right now or around now", None, "I am studying for the TOEIC test."),
    ("Past Simple", "Completed action in the past", None, "They finished the project yesterday."),
    ("Present Perfect", "Past action with present relevance", None, "I have already submitted the report."),
    ("Past Perfect", "Action completed before another past action", None, "By the time he arrived, she had left."),
    ("Future Simple (will)", "Predictions, promises, spontaneous decisions", None, "I will call you tomorrow."),
    ("Going to", "Plans and intentions already decided", None, "We are going to launch next month."),
    ("First Conditional", "Real/possible future condition", None, "If it rains, I will take an umbrella."),
    ("Second Conditional", "Unreal/hypothetical present", None, "If I were rich, I would travel the world."),
    ("Third Conditional", "Unreal past condition", None, "If I had studied harder, I would have passed."),
    ("Passive Voice", "Focus on the action, not the doer", None, "The report was written by the manager."),
    ("Reported Speech", "Retelling what someone said", None, "He said that he was busy."),
    ("Relative Clauses", "Adding info about a noun with who/which/that", None, "The man who called you is my boss."),
    ("Gerund vs Infinitive", "Some verbs take -ing, some take to + verb", None, "I enjoy reading. / I want to read."),
    ("Modal Verbs", "Express ability, permission, obligation", None, "You must submit the form. / She can speak French."),
    ("Comparatives", "Comparing two things", None, "This method is more efficient than the old one."),
    ("Superlatives", "The highest degree of comparison", None, "This is the most effective strategy."),
    ("Articles (a/an/the)", "Definite vs indefinite reference", None, "I read a book. The book was interesting."),
    ("Prepositions of Time", "at/on/in for time expressions", None, "at 3pm / on Monday / in January"),
    ("Prepositions of Place", "at/on/in for locations", None, "at the office / on the table / in the room"),
    ("Conjunctions", "Connecting words: and, but, or, so, because", None, "I was tired, but I kept working."),
    ("Subject-Verb Agreement", "Singular subject → singular verb", None, "Each employee has a badge. (not 'have')"),
    ("Tag Questions", "Short question at end for confirmation", None, "You're coming to the meeting, aren't you?"),
    ("Countable vs Uncountable", "Use many/few vs much/little", None, "How much time? / How many people?"),
]

ENGLISH_GRAMMAR_QUIZ = [
    {"q": "Choose the correct sentence:", "type": "multiple_choice", "options": ["She don't like coffee.", "She doesn't likes coffee.", "She doesn't like coffee.", "She not like coffee."], "answer": "She doesn't like coffee.", "explain": "Present simple negative: subject + doesn't + base verb."},
    {"q": "Fill in: 'By the time we arrived, the movie ___.'", "type": "fill_blank", "options": [], "answer": "had started", "explain": "Past perfect for action completed before another past action."},
    {"q": "Which sentence uses passive voice correctly?", "type": "multiple_choice", "options": ["The cake baked by my mom.", "The cake was baked by my mom.", "The cake is bake by my mom.", "The cake were baked by my mom."], "answer": "The cake was baked by my mom.", "explain": "Passive = be + past participle."},
    {"q": "Fill in: 'If I ___ you, I would accept the offer.'", "type": "fill_blank", "options": [], "answer": "were", "explain": "Second conditional: If + past simple (were for all subjects)."},
    {"q": "'I enjoy ___' — which form follows 'enjoy'?", "type": "multiple_choice", "options": ["to read", "reading", "read", "reads"], "answer": "reading", "explain": "Enjoy + gerund (-ing form)."},
    {"q": "Fill in: 'Each employee ___ required to attend.'", "type": "fill_blank", "options": [], "answer": "is", "explain": "Each + singular noun = singular verb."},
    {"q": "Choose the correct preposition: 'The meeting is ___ Monday.'", "type": "multiple_choice", "options": ["in", "at", "on", "by"], "answer": "on", "explain": "Use 'on' with days: on Monday, on Friday."},
    {"q": "Fill in: 'This is the ___ solution we've found so far.'", "type": "fill_blank", "options": [], "answer": "best", "explain": "Superlative of 'good' = best."},
]
