"""Add theme_settings table

Revision ID: 3d1ee84e2369
Revises: 
Create Date: 2025-12-07 18:35:54.303600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1ee84e2369'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theme_settings_id'), 'theme_settings', ['id'], unique=False)
    op.create_index(op.f('ix_theme_settings_key'), 'theme_settings', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theme_settings_key'), table_name='theme_settings')
    op.drop_index(op.f('ix_theme_settings_id'), table_name='theme_settings')
    op.drop_table('theme_settings')
    # ### end Alembic commands ###
